export type ListingCategory =
  | "digital_marketing"
  | "property_sale"
  | "property_rental"
  | "apartment_sale"
  | "apartment_rental"
  | "transport"
  | "communications";

export const CATEGORY_LABELS: Record<ListingCategory, string> = {
  digital_marketing: "Digital Marketing",
  property_sale: "Property for Sale",
  property_rental: "Property to Rent",
  apartment_sale: "Apartment for Sale",
  apartment_rental: "Apartment to Rent",
  transport: "Transport & Vehicles",
  communications: "Communications & Tech",
};

export const CATEGORY_ICONS: Record<ListingCategory, string> = {
  digital_marketing: "📈",
  property_sale: "🏡",
  property_rental: "🏠",
  apartment_sale: "🏢",
  apartment_rental: "🏬",
  transport: "🚗",
  communications: "📡",
};

export type MarketplaceListing = {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: ListingCategory;
  price: number;
  priceUnit?: string;
  negotiable?: boolean;
  images: string[];
  badge?: "featured" | "new" | "hot" | "sale";
  location?: string;
  city?: string;
  province?: string;
  // Property fields
  bedrooms?: number;
  bathrooms?: number;
  garages?: number;
  erf?: number;
  floor?: number;
  furnished?: boolean;
  petFriendly?: boolean;
  amenities?: string[];
  // Vehicle fields
  make?: string;
  model?: string;
  year?: number;
  mileage?: number;
  fuelType?: string;
  // Service fields
  deliveryTime?: string;
  features?: string[];
  // Metrics
  viewCount: number;
  inquiryCount: number;
  sellerName: string;
  sellerLocation: string;
};

export const SEED_LISTINGS: MarketplaceListing[] = [
  // ── Digital Marketing ──────────────────────────────────────────
  {
    id: "dm-seo-starter",
    slug: "dm-seo-starter",
    title: "SEO Starter Package",
    description: "Boost your organic rankings with foundational SEO.",
    category: "digital_marketing",
    price: 4999,
    priceUnit: "once-off",
    images: ["https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&h=400&fit=crop"],
    badge: "featured",
    features: ["50 keywords", "On-page optimisation (10 pages)", "Technical SEO audit", "Monthly report"],
    deliveryTime: "2–3 weeks",
    viewCount: 214,
    inquiryCount: 18,
    sellerName: "DigitalEdge Agency",
    sellerLocation: "Sandton, JHB",
  },
  {
    id: "dm-social",
    slug: "dm-social",
    title: "Social Media Management",
    description: "Full social media management across 4 major platforms.",
    category: "digital_marketing",
    price: 7990,
    priceUnit: "per month",
    images: ["https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=600&h=400&fit=crop"],
    badge: "hot",
    features: ["Instagram, Facebook, X, LinkedIn", "20 posts/month", "Community management", "Analytics report"],
    deliveryTime: "Ongoing",
    viewCount: 301,
    inquiryCount: 31,
    sellerName: "DigitalEdge Agency",
    sellerLocation: "Sandton, JHB",
  },
  {
    id: "dm-google-ads",
    slug: "dm-google-ads",
    title: "Google Ads Management",
    description: "Expert PPC campaigns that drive qualified leads.",
    category: "digital_marketing",
    price: 8990,
    priceUnit: "per month",
    images: ["https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=600&h=400&fit=crop"],
    badge: "new",
    features: ["Campaign setup", "Keyword research", "Ad copy (10 variants)", "Weekly reports"],
    deliveryTime: "1 week setup",
    viewCount: 189,
    inquiryCount: 22,
    sellerName: "DigitalEdge Agency",
    sellerLocation: "Sandton, JHB",
  },
  // ── Properties for Sale ────────────────────────────────────────
  {
    id: "ps-sandton-house",
    slug: "ps-sandton-house",
    title: "4 Bed Family Home — Sandton",
    description: "Spacious modern family home in a secure estate. Double garage, heated pool, chef's kitchen.",
    category: "property_sale",
    price: 4850000,
    negotiable: true,
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&h=400&fit=crop"],
    badge: "featured",
    bedrooms: 4,
    bathrooms: 3,
    garages: 2,
    erf: 980,
    city: "Sandton",
    province: "Gauteng",
    amenities: ["Pool", "Garden", "Fibre", "Solar panels", "Security system"],
    viewCount: 547,
    inquiryCount: 43,
    sellerName: "Apex Properties",
    sellerLocation: "Sandton, JHB",
  },
  {
    id: "ps-cape-town-home",
    slug: "ps-cape-town-home",
    title: "3 Bed Home with Ocean View — Cape Town",
    description: "Stunning ocean-view property in Bloubergstrand. Wrap-around deck, modern finishes.",
    category: "property_sale",
    price: 3200000,
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop"],
    badge: "hot",
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    erf: 650,
    city: "Bloubergstrand",
    province: "Western Cape",
    amenities: ["Ocean view", "Deck", "Fibre", "Open plan"],
    viewCount: 812,
    inquiryCount: 67,
    sellerName: "Cape Coastal Properties",
    sellerLocation: "Cape Town, WC",
  },
  // ── Properties to Rent ─────────────────────────────────────────
  {
    id: "pr-rosebank-house",
    slug: "pr-rosebank-house",
    title: "3 Bed House to Rent — Rosebank",
    description: "Beautiful 3-bedroom house in a safe street. Garden, double garage, close to schools.",
    category: "property_rental",
    price: 24500,
    priceUnit: "per month",
    negotiable: true,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop"],
    bedrooms: 3,
    bathrooms: 2,
    garages: 2,
    erf: 700,
    city: "Rosebank",
    province: "Gauteng",
    petFriendly: true,
    amenities: ["Garden", "Fibre", "Double garage"],
    viewCount: 324,
    inquiryCount: 29,
    sellerName: "Urban Rentals",
    sellerLocation: "Rosebank, JHB",
  },
  {
    id: "pr-pretoria-house",
    slug: "pr-pretoria-house",
    title: "4 Bed House with Pool — Pretoria East",
    description: "Spacious family home to rent, pool, large garden, in sought-after security estate.",
    category: "property_rental",
    price: 18900,
    priceUnit: "per month",
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&h=400&fit=crop"],
    bedrooms: 4,
    bathrooms: 3,
    garages: 2,
    city: "Pretoria East",
    province: "Gauteng",
    amenities: ["Pool", "Garden", "Fibre", "Security estate"],
    viewCount: 198,
    inquiryCount: 14,
    sellerName: "PTA Rentals",
    sellerLocation: "Pretoria, GP",
  },
  // ── Apartments for Sale ────────────────────────────────────────
  {
    id: "as-sandton-apt",
    slug: "as-sandton-apt",
    title: "2 Bed Luxury Apartment — Sandton CBD",
    description: "High-rise luxury apartment in Sandton CBD. Floor-to-ceiling windows, concierge, gym.",
    category: "apartment_sale",
    price: 2150000,
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop"],
    badge: "featured",
    bedrooms: 2,
    bathrooms: 2,
    floor: 18,
    city: "Sandton CBD",
    province: "Gauteng",
    furnished: false,
    amenities: ["Gym", "Rooftop pool", "24hr concierge", "Underground parking"],
    viewCount: 421,
    inquiryCount: 38,
    sellerName: "Sandton Estates",
    sellerLocation: "Sandton, JHB",
  },
  {
    id: "as-durban-apt",
    slug: "as-durban-apt",
    title: "1 Bed Beachfront Apartment — Umhlanga",
    description: "Stunning beachfront apartment in Umhlanga. Walk to the beach, modern finishes.",
    category: "apartment_sale",
    price: 1750000,
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop"],
    badge: "new",
    bedrooms: 1,
    bathrooms: 1,
    floor: 6,
    city: "Umhlanga",
    province: "KwaZulu-Natal",
    furnished: true,
    amenities: ["Beach access", "Pool", "Parking", "Security"],
    viewCount: 289,
    inquiryCount: 24,
    sellerName: "KZN Properties",
    sellerLocation: "Umhlanga, KZN",
  },
  // ── Apartments to Rent ─────────────────────────────────────────
  {
    id: "ar-jhb-studio",
    slug: "ar-jhb-studio",
    title: "Modern Studio Apartment — Braamfontein",
    description: "Stylish studio in the heart of Braamfontein. Fully furnished, fast fibre, rooftop access.",
    category: "apartment_rental",
    price: 8900,
    priceUnit: "per month",
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop"],
    bedrooms: 0,
    bathrooms: 1,
    floor: 4,
    city: "Braamfontein",
    province: "Gauteng",
    furnished: true,
    petFriendly: false,
    amenities: ["Rooftop lounge", "Fibre included", "Secure parking", "Laundry"],
    viewCount: 412,
    inquiryCount: 51,
    sellerName: "Urban Pads",
    sellerLocation: "JHB",
  },
  {
    id: "ar-ct-2bed",
    slug: "ar-ct-2bed",
    title: "2 Bed Apartment — De Waterkant, Cape Town",
    description: "Trendy 2-bedroom in De Waterkant. Close to V&A Waterfront, perfect for young professionals.",
    category: "apartment_rental",
    price: 19500,
    priceUnit: "per month",
    images: ["https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=400&fit=crop"],
    badge: "hot",
    bedrooms: 2,
    bathrooms: 1,
    floor: 3,
    city: "De Waterkant",
    province: "Western Cape",
    furnished: true,
    amenities: ["Balcony", "Fibre", "Secure parking", "Near Waterfront"],
    viewCount: 534,
    inquiryCount: 62,
    sellerName: "Cape Luxury Rentals",
    sellerLocation: "Cape Town, WC",
  },
  // ── Transport ──────────────────────────────────────────────────
  {
    id: "tr-bmw-3series",
    slug: "tr-bmw-3series",
    title: "2022 BMW 3 Series 320i",
    description: "Immaculate BMW 3 Series. One owner, full service history, leather seats, sunroof.",
    category: "transport",
    price: 469000,
    negotiable: true,
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&h=400&fit=crop"],
    badge: "featured",
    make: "BMW",
    model: "3 Series 320i",
    year: 2022,
    mileage: 32000,
    fuelType: "Petrol",
    city: "Sandton",
    province: "Gauteng",
    viewCount: 673,
    inquiryCount: 54,
    sellerName: "Premium Motors",
    sellerLocation: "Sandton, JHB",
  },
  {
    id: "tr-toyota-hilux",
    slug: "tr-toyota-hilux",
    title: "2021 Toyota Hilux 2.8 GD-6 4x4",
    description: "Top-of-the-line Hilux Legend. Bull bar, canopy, leather, excellent condition.",
    category: "transport",
    price: 559000,
    images: ["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&h=400&fit=crop"],
    badge: "hot",
    make: "Toyota",
    model: "Hilux 2.8 GD-6 Legend",
    year: 2021,
    mileage: 48000,
    fuelType: "Diesel",
    city: "Pretoria",
    province: "Gauteng",
    viewCount: 891,
    inquiryCount: 78,
    sellerName: "Bakkie Kingdom",
    sellerLocation: "Pretoria, GP",
  },
  {
    id: "tr-minibus",
    slug: "tr-minibus",
    title: "2019 Toyota HiAce Quantum Minibus",
    description: "Well-maintained 14-seater minibus taxi. Roadworthy, reliable for daily routes.",
    category: "transport",
    price: 265000,
    negotiable: true,
    images: ["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&h=400&fit=crop"],
    make: "Toyota",
    model: "HiAce Quantum",
    year: 2019,
    mileage: 210000,
    fuelType: "Diesel",
    city: "Johannesburg",
    province: "Gauteng",
    viewCount: 312,
    inquiryCount: 29,
    sellerName: "Taxi Fleet SA",
    sellerLocation: "JHB",
  },
  // ── Communications ─────────────────────────────────────────────
  {
    id: "com-fibre",
    slug: "com-fibre",
    title: "Business Fibre Installation Package",
    description: "Enterprise-grade fibre internet installed and configured. 200Mbps uncapped, 99.9% uptime SLA.",
    category: "communications",
    price: 3499,
    priceUnit: "per month",
    images: ["https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop"],
    badge: "featured",
    features: ["200Mbps uncapped", "Static IP", "24/7 support", "99.9% SLA", "Free router"],
    deliveryTime: "3–5 business days",
    viewCount: 267,
    inquiryCount: 33,
    sellerName: "ConnectSA",
    sellerLocation: "Johannesburg",
  },
  {
    id: "com-voip",
    slug: "com-voip",
    title: "VoIP Business Phone System",
    description: "Cloud-based VoIP system for your business. Unlimited local calls, easy setup, mobile app.",
    category: "communications",
    price: 1290,
    priceUnit: "per month",
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop"],
    badge: "new",
    features: ["Unlimited local calls", "Mobile app", "Call recording", "IVR menu", "10 extensions"],
    deliveryTime: "1–2 business days",
    viewCount: 143,
    inquiryCount: 19,
    sellerName: "TeleSmart SA",
    sellerLocation: "Cape Town, WC",
  },
  {
    id: "com-cctv",
    slug: "com-cctv",
    title: "CCTV Security System Installation",
    description: "8-camera HD CCTV system with remote monitoring. Full installation, night vision, 30-day storage.",
    category: "communications",
    price: 8900,
    priceUnit: "once-off",
    negotiable: true,
    images: ["https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&h=400&fit=crop"],
    features: ["8x HD cameras", "Night vision", "Remote monitoring app", "30-day storage", "Motion alerts"],
    deliveryTime: "2–3 days installation",
    viewCount: 198,
    inquiryCount: 27,
    sellerName: "SecureTech SA",
    sellerLocation: "Pretoria, GP",
  },
];
